### PR TITLE
Add support for attaching java debugger and pydevd debugger

### PR DESCRIPTION
**Pull request by brownzach125**
@michalsustr I believe you said you were interested in creating a way attaching debuggers to the bots. 
Is this the kind of thing you were thinking of?
Just thought I would create this pull request as a talking point if you were then.

### CODE REVIEW

**Comment by michalsustr** [comment]
Wow, looks interesting! Can't test it now, but is this the way how you could attach Intellij debugger? https://stackoverflow.com/a/30793101/1233675

**Comment by brownzach125** [comment]
Yes, but I've only tested it with eclipse. But it's just the Java remote
debug API. My change makes the bot run a debug server that can be attached
to.

**Comment by michalsustr** [comment]
I can't make it work. It seems the debugger does not run on the port:
```
sudo lsof -i
[sudo] password for starcraft: 
COMMAND   PID      USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
x11vnc     42 starcraft   10u  IPv4 2289633      0t0  TCP *:5900 (LISTEN)
x11vnc     42 starcraft   11u  IPv6 2289634      0t0  TCP *:5900 (LISTEN)
wineserve  51 starcraft  225u  IPv4 2292180      0t0  UDP *:6111 
wineserve  51 starcraft  227u  IPv4 2292181      0t0  UDP *:6112 
StarCraft 116 starcraft   30u  IPv4 2292180      0t0  UDP *:6111 
StarCraft 116 starcraft   38u  IPv4 2292180      0t0  UDP *:6111 
StarCraft 116 starcraft   41u  IPv4 2292181      0t0  UDP *:6112 
StarCraft 116 starcraft   49u  IPv4 2292181      0t0  UDP *:6112 
StarCraft 116 starcraft   54u  IPv4 2292181      0t0  UDP *:6112
```

I've used Windows x86 jre-8u161-windows-i586.tar.gz
Shouldn't it use a JDK?

**Comment by michalsustr** [comment]
It works now :) Thanks! 

One minor issue - `drop_players = OFF` is not respected in `bwapi.ini`, did you encounter this?

**Comment by brownzach125** [comment]
I did notice my bots were starting to be dropped if I paused them for too long. I didn't check to see if drop_players = OFF was set.

**Pull request merged**
