### PR TITLE
Add ability specify host to which connect VNC viewers

### PR DESCRIPTION
**Pull request by kant2002**
Added command line parameter `--vnc_host`. By default `localhost`.
This is required if you run on the Docker Toolbox which run all docker containers inside VM
By giving ability to specify that as parameter, there no need to run VNC manually each time

### CODE REVIEW

**Comment by michalsustr** [comment]
Couldn't we find that address automatically?

https://docs.docker.com/machine/reference/ip/

**Comment by kant2002** [comment]
a) I'm not that familiar with codebase to include detection of docker-machine
b) I think having ability set explicitly host is good on it's own. Since that way we account for the unknown scenarios, maybe future scenarios. So I decide go easy and fast way to solve my need. If you want docker-machine detection, I could add that.

**Comment by michalsustr** [comment]
b) Yes, I agree it'a a good idea. 

I can add it, can you just confirm what CLI should I run to get it? 
`docker-machine ip ???`

**Comment by kant2002** [comment]
Yes, `docker-machine-ip` do the trick. If you want `docker-machine ip` detection, maybe I could do that as separate PR ?

**Comment by michalsustr** [comment]
Ok, sounds good.

**Pull request merged**
